/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

// Load environment variables from .env file
import dotenv from "dotenv";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

// Load .env from project root (two levels up from this file)  
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const envPath = resolve(__dirname, "../../../.env");
// Configure dotenv to suppress all output for MCP compatibility
process.env['DOTENV_CONFIG_QUIET'] = 'true';
dotenv.config({ path: envPath, debug: false, override: false });

import { buildApplication, buildRouteMap, run } from "@stricli/core";
import process from "node:process";
import { buildContext } from "./cli.js";
import { authCommand } from "./cli/auth/command.js";
import { startCommand } from "./cli/start/command.js";

const routes = buildRouteMap({
  routes: {
    auth: authCommand,
    start: startCommand,
  },
  docs: {
    brief: "MCP server CLI",
  },
});

export const app = buildApplication(routes, {
  name: "mcp",
  versionInfo: {
    currentVersion: "0.0.1",
  },
});

run(app, process.argv.slice(2), buildContext(process));
