/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { GraphMailCalendarSDKCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$createMeEvent } from "./tools/createMeEvent.js";
import { tool$deleteMeEvent } from "./tools/deleteMeEvent.js";
import { tool$deleteMeMessage } from "./tools/deleteMeMessage.js";
import { tool$getMeCalendarView } from "./tools/getMeCalendarView.js";
import { tool$getMeEvent } from "./tools/getMeEvent.js";
import { tool$getMeMessage } from "./tools/getMeMessage.js";
import { tool$listMeEvents } from "./tools/listMeEvents.js";
import { tool$listMeMessages } from "./tools/listMeMessages.js";
import { tool$listUserEvents } from "./tools/listUserEvents.js";
import { tool$listUserMessages } from "./tools/listUserMessages.js";
import { tool$sendMail } from "./tools/sendMail.js";
import { tool$updateMeEvent } from "./tools/updateMeEvent.js";
import { tool$updateMeMessage } from "./tools/updateMeMessage.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  getSDK?: () => GraphMailCalendarSDKCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "GraphMailCalendarSDK",
    version: "0.0.1",
  });

  const getClient = deps.getSDK || (() =>
    new GraphMailCalendarSDKCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$listMeMessages);
  tool(tool$getMeMessage);
  tool(tool$updateMeMessage);
  tool(tool$deleteMeMessage);
  tool(tool$listUserMessages);
  tool(tool$sendMail);
  tool(tool$listMeEvents);
  tool(tool$createMeEvent);
  tool(tool$getMeEvent);
  tool(tool$updateMeEvent);
  tool(tool$deleteMeEvent);
  tool(tool$listUserEvents);
  tool(tool$getMeCalendarView);

  return server;
}
