/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EmailAddress, EmailAddress$zodSchema } from "./emailaddress.js";

export const Type$zodSchema = z.enum([
  "required",
  "optional",
  "resource",
]);

export type Type = z.infer<typeof Type$zodSchema>;

export type Attendee = { type?: Type | undefined; emailAddress: EmailAddress };

export const Attendee$zodSchema: z.ZodType<Attendee, z.ZodTypeDef, unknown> = z
  .object({
    emailAddress: EmailAddress$zodSchema,
    type: Type$zodSchema.optional(),
  });
