/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Event, Event$zodSchema } from "./event.js";

export type CreateMeEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Event?: Event | undefined;
};

export const CreateMeEventResponse$zodSchema: z.ZodType<
  CreateMeEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Event: Event$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
