/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DateTimeTimeZone = { dateTime: string; timeZone: string };

export const DateTimeTimeZone$zodSchema: z.ZodType<
  DateTimeTimeZone,
  z.ZodTypeDef,
  unknown
> = z.object({
  dateTime: z.string(),
  timeZone: z.string(),
});
