/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteMeMessageRequest = { messageId: string };

export const DeleteMeMessageRequest$zodSchema: z.ZodType<
  DeleteMeMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: z.string(),
});

export type DeleteMeMessageResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteMeMessageResponse$zodSchema: z.ZodType<
  DeleteMeMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
