/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteMeEventRequest = { eventId: string };

export const DeleteMeEventRequest$zodSchema: z.ZodType<
  DeleteMeEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  eventId: z.string(),
});

export type DeleteMeEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteMeEventResponse$zodSchema: z.ZodType<
  DeleteMeEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
