/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EmailAddress = { name?: string | undefined; address: string };

export const EmailAddress$zodSchema: z.ZodType<
  EmailAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string(),
  name: z.string().optional(),
});
