/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Attendee, Attendee$zodSchema } from "./attendee.js";
import {
  DateTimeTimeZone,
  DateTimeTimeZone$zodSchema,
} from "./datetimetimezone.js";
import { ItemBody, ItemBody$zodSchema } from "./itembody.js";
import { Location, Location$zodSchema } from "./location.js";
import { Recipient, Recipient$zodSchema } from "./recipient.js";

export type Event = {
  id?: string | undefined;
  subject?: string | undefined;
  body?: ItemBody | undefined;
  start?: DateTimeTimeZone | undefined;
  end?: DateTimeTimeZone | undefined;
  location?: Location | undefined;
  attendees?: Array<Attendee> | undefined;
  organizer?: Recipient | undefined;
  isAllDay?: boolean | undefined;
};

export const Event$zodSchema: z.ZodType<Event, z.ZodTypeDef, unknown> = z
  .object({
    attendees: z.array(Attendee$zodSchema).optional(),
    body: ItemBody$zodSchema.optional(),
    end: DateTimeTimeZone$zodSchema.optional(),
    id: z.string().optional(),
    isAllDay: z.boolean().optional(),
    location: Location$zodSchema.optional(),
    organizer: Recipient$zodSchema.optional(),
    start: DateTimeTimeZone$zodSchema.optional(),
    subject: z.string().optional(),
  });
