/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Message, Message$zodSchema } from "./message.js";

export type GetMeMessageRequest = { messageId: string };

export const GetMeMessageRequest$zodSchema: z.ZodType<
  GetMeMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  messageId: z.string(),
});

export type GetMeMessageResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Message?: Message | undefined;
};

export const GetMeMessageResponse$zodSchema: z.ZodType<
  GetMeMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Message: Message$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
