/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Event, Event$zodSchema } from "./event.js";

export type GetMeEventRequest = { eventId: string };

export const GetMeEventRequest$zodSchema: z.ZodType<
  GetMeEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  eventId: z.string(),
});

export type GetMeEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Event?: Event | undefined;
};

export const GetMeEventResponse$zodSchema: z.ZodType<
  GetMeEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Event: Event$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
