/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PagedEvents, PagedEvents$zodSchema } from "./pagedevents.js";

export type GetMeCalendarViewRequest = {
  startDateTime: string;
  endDateTime: string;
  Dollar_select?: string | undefined;
};

export const GetMeCalendarViewRequest$zodSchema: z.ZodType<
  GetMeCalendarViewRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_select: z.string().optional(),
  endDateTime: z.string().datetime({ offset: true }),
  startDateTime: z.string().datetime({ offset: true }),
});

export type GetMeCalendarViewResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  PagedEvents?: PagedEvents | undefined;
};

export const GetMeCalendarViewResponse$zodSchema: z.ZodType<
  GetMeCalendarViewResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  PagedEvents: PagedEvents$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
