/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ContentType$zodSchema = z.enum([
  "Text",
  "HTML",
]);

export type ContentType = z.infer<typeof ContentType$zodSchema>;

export type ItemBody = {
  contentType?: ContentType | undefined;
  content?: string | undefined;
};

export const ItemBody$zodSchema: z.ZodType<ItemBody, z.ZodTypeDef, unknown> = z
  .object({
    content: z.string().optional(),
    contentType: ContentType$zodSchema.optional(),
  });
