/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PagedMessages, PagedMessages$zodSchema } from "./pagedmessages.js";

export type ListMeMessagesRequest = {
  Dollar_top?: number | undefined;
  Dollar_filter?: string | undefined;
  Dollar_select?: string | undefined;
  Dollar_orderby?: string | undefined;
};

export const ListMeMessagesRequest$zodSchema: z.ZodType<
  ListMeMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_filter: z.string().optional(),
  Dollar_orderby: z.string().optional(),
  Dollar_select: z.string().optional(),
  Dollar_top: z.number().int().optional(),
});

export type ListMeMessagesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  PagedMessages?: PagedMessages | undefined;
};

export const ListMeMessagesResponse$zodSchema: z.ZodType<
  ListMeMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  PagedMessages: PagedMessages$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
