/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PagedEvents, PagedEvents$zodSchema } from "./pagedevents.js";

export type ListUserEventsRequest = { userId: string };

export const ListUserEventsRequest$zodSchema: z.ZodType<
  ListUserEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string().describe("User id or UPN"),
});

export type ListUserEventsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  PagedEvents?: PagedEvents | undefined;
};

export const ListUserEventsResponse$zodSchema: z.ZodType<
  ListUserEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  PagedEvents: PagedEvents$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
