/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PagedMessages, PagedMessages$zodSchema } from "./pagedmessages.js";

export type ListUserMessagesRequest = { userId: string };

export const ListUserMessagesRequest$zodSchema: z.ZodType<
  ListUserMessagesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string().describe("User id or UPN"),
});

export type ListUserMessagesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  PagedMessages?: PagedMessages | undefined;
};

export const ListUserMessagesResponse$zodSchema: z.ZodType<
  ListUserMessagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  PagedMessages: PagedMessages$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
