/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PagedEvents, PagedEvents$zodSchema } from "./pagedevents.js";

export type ListMeEventsRequest = {
  Dollar_top?: number | undefined;
  Dollar_filter?: string | undefined;
  Dollar_select?: string | undefined;
};

export const ListMeEventsRequest$zodSchema: z.ZodType<
  ListMeEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Dollar_filter: z.string().optional(),
  Dollar_select: z.string().optional(),
  Dollar_top: z.number().int().optional(),
});

export type ListMeEventsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  PagedEvents?: PagedEvents | undefined;
};

export const ListMeEventsResponse$zodSchema: z.ZodType<
  ListMeEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  PagedEvents: PagedEvents$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
