/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Location = { displayName?: string | undefined };

export const Location$zodSchema: z.ZodType<Location, z.ZodTypeDef, unknown> = z
  .object({
    displayName: z.string().optional(),
  });
