/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ItemBody, ItemBody$zodSchema } from "./itembody.js";
import { Recipient, Recipient$zodSchema } from "./recipient.js";

export type Message = {
  id?: string | undefined;
  subject?: string | undefined;
  body?: ItemBody | undefined;
  from?: Recipient | undefined;
  sender?: Recipient | undefined;
  toRecipients?: Array<Recipient> | undefined;
  ccRecipients?: Array<Recipient> | undefined;
  bccRecipients?: Array<Recipient> | undefined;
  receivedDateTime?: string | undefined;
  sentDateTime?: string | undefined;
  conversationId?: string | undefined;
};

export const Message$zodSchema: z.ZodType<Message, z.ZodTypeDef, unknown> = z
  .object({
    bccRecipients: z.array(Recipient$zodSchema).optional(),
    body: ItemBody$zodSchema.optional(),
    ccRecipients: z.array(Recipient$zodSchema).optional(),
    conversationId: z.string().optional(),
    from: Recipient$zodSchema.optional(),
    id: z.string().optional(),
    receivedDateTime: z.string().datetime({ offset: true }).optional(),
    sender: Recipient$zodSchema.optional(),
    sentDateTime: z.string().datetime({ offset: true }).optional(),
    subject: z.string().optional(),
    toRecipients: z.array(Recipient$zodSchema).optional(),
  });
