/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Message, Message$zodSchema } from "./message.js";

export type PagedMessages = {
  value?: Array<Message> | undefined;
  atOdataNextLink?: string | undefined;
};

export const PagedMessages$zodSchema: z.ZodType<
  PagedMessages,
  z.ZodTypeDef,
  unknown
> = z.object({
  atOdataNextLink: z.string().optional(),
  value: z.array(Message$zodSchema).optional(),
});
