/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Event, Event$zodSchema } from "./event.js";

export type PagedEvents = {
  value?: Array<Event> | undefined;
  atOdataNextLink?: string | undefined;
};

export const PagedEvents$zodSchema: z.ZodType<
  PagedEvents,
  z.ZodTypeDef,
  unknown
> = z.object({
  atOdataNextLink: z.string().optional(),
  value: z.array(Event$zodSchema).optional(),
});
