/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EmailAddress, EmailAddress$zodSchema } from "./emailaddress.js";

export type Recipient = { emailAddress: EmailAddress };

export const Recipient$zodSchema: z.ZodType<Recipient, z.ZodTypeDef, unknown> =
  z.object({
    emailAddress: EmailAddress$zodSchema,
  });
