/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SendMailResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const SendMailResponse$zodSchema: z.ZodType<
  SendMailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
