/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Message, Message$zodSchema } from "./message.js";

export type SendMailRequest = {
  message: Message;
  saveToSentItems?: boolean | undefined;
};

export const SendMailRequest$zodSchema: z.ZodType<
  SendMailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: Message$zodSchema,
  saveToSentItems: z.boolean().optional(),
});
