/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Event, Event$zodSchema } from "./event.js";

export type UpdateMeEventRequest = { eventId: string; Event: Event };

export const UpdateMeEventRequest$zodSchema: z.ZodType<
  UpdateMeEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Event: Event$zodSchema,
  eventId: z.string(),
});

export type UpdateMeEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Event?: Event | undefined;
};

export const UpdateMeEventResponse$zodSchema: z.ZodType<
  UpdateMeEventResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Event: Event$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
