/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Message, Message$zodSchema } from "./message.js";

export type UpdateMeMessageRequest = { messageId: string; Message: Message };

export const UpdateMeMessageRequest$zodSchema: z.ZodType<
  UpdateMeMessageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Message: Message$zodSchema,
  messageId: z.string(),
});

export type UpdateMeMessageResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Message?: Message | undefined;
};

export const UpdateMeMessageResponse$zodSchema: z.ZodType<
  UpdateMeMessageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  Message: Message$zodSchema.optional(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
