/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deleteMeMessage } from "../../funcs/deleteMeMessage.js";
import { DeleteMeMessageRequest$zodSchema } from "../../models/deletememessageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteMeMessageRequest$zodSchema,
};

export const tool$deleteMeMessage: ToolDefinition<typeof args> = {
  name: "delete-me-message",
  description: `Delete a message`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deleteMeMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
