/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getMeCalendarView } from "../../funcs/getMeCalendarView.js";
import { GetMeCalendarViewRequest$zodSchema } from "../../models/getmecalendarviewop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMeCalendarViewRequest$zodSchema,
};

export const tool$getMeCalendarView: ToolDefinition<typeof args> = {
  name: "get-me-calendar-view",
  description: `Get a calendar view within a time range

Requires startDateTime and endDateTime query parameters.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getMeCalendarView(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
