/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { getMeEvent } from "../../funcs/getMeEvent.js";
import { GetMeEventRequest$zodSchema } from "../../models/getmeeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMeEventRequest$zodSchema,
};

export const tool$getMeEvent: ToolDefinition<typeof args> = {
  name: "get-me-event",
  description: `Get an event`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await getMeEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
