/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listMeMessages } from "../../funcs/listMeMessages.js";
import { ListMeMessagesRequest$zodSchema } from "../../models/listmemessagesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListMeMessagesRequest$zodSchema.optional(),
};

export const tool$listMeMessages: ToolDefinition<typeof args> = {
  name: "list-me-messages",
  description: `List messages in the signed-in user's mailbox`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listMeMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
