/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listMeEvents } from "../../funcs/listMeEvents.js";
import { ListMeEventsRequest$zodSchema } from "../../models/listmeeventsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListMeEventsRequest$zodSchema.optional(),
};

export const tool$listMeEvents: ToolDefinition<typeof args> = {
  name: "list-me-events",
  description: `List events from the user's default calendar`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listMeEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
