/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listUserEvents } from "../../funcs/listUserEvents.js";
import { ListUserEventsRequest$zodSchema } from "../../models/listusereventsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUserEventsRequest$zodSchema,
};

export const tool$listUserEvents: ToolDefinition<typeof args> = {
  name: "list-user-events",
  description: `List events for a user`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listUserEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
