/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listUserMessages } from "../../funcs/listUserMessages.js";
import { ListUserMessagesRequest$zodSchema } from "../../models/listusermessagesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUserMessagesRequest$zodSchema,
};

export const tool$listUserMessages: ToolDefinition<typeof args> = {
  name: "list-user-messages",
  description: `List messages for a user`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listUserMessages(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
