/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sendMail } from "../../funcs/sendMail.js";
import { SendMailRequest$zodSchema } from "../../models/sendmailrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SendMailRequest$zodSchema,
};

export const tool$sendMail: ToolDefinition<typeof args> = {
  name: "send-mail",
  description: `Send an email as the signed-in user`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sendMail(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
