/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateMeEvent } from "../../funcs/updateMeEvent.js";
import { UpdateMeEventRequest$zodSchema } from "../../models/updatemeeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateMeEventRequest$zodSchema,
};

export const tool$updateMeEvent: ToolDefinition<typeof args> = {
  name: "update-me-event",
  description: `Update an event`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await updateMeEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
