/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { updateMeMessage } from "../../funcs/updateMeMessage.js";
import { UpdateMeMessageRequest$zodSchema } from "../../models/updatememessageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateMeMessageRequest$zodSchema,
};

export const tool$updateMeMessage: ToolDefinition<typeof args> = {
  name: "update-me-message",
  description: `Update a specific message`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await updateMeMessage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
